### ISSUE TITLE
contribution to iterationt

### ISSUE THREAD

**Issue by rhjdvsgsgks** [MineGraphCN/MGC_Docs#56]
hi

i wrote some patch for iterationt 3.2, to fix the bug on my machine and add some minor features. can the link of them being included to this repo?

links:
fix shader compilation & visual glitch
https://github.com/IrisShaders/Iris/issues/1030#issuecomment-2399424802
pq tonemapping for hdr support
https://github.com/IrisShaders/Iris/issues/2282#issuecomment-2400800905

**Comment by shaoxiu** [comment]
Thanks for your help. We have provided two patches to iterationT's author for review. Additionally, due to the presence of illegal content in iterationT's code, please do not mention it in iris shader's issue or other foreign project communities.

**Comment by rhjdvsgsgks** [comment]
SEUS_PTGI_GFME is also a modified version of seus shader. but accepted by iris community. can iterationt be released in a similar manner to avoid copyright issue from seus shader?

**Comment by ExDragine** [comment]
> SEUS_PTGI_GFME is also a modified version of seus shader. but accepted by iris community. can iterationt be released in a similar manner to avoid copyright issue from seus shader?

Thank you for your suggestion regarding compliance within the community. However, we have already discussed this idea and concluded that its chances of success are quite limited. One of the main reasons is that the Iris shader community largely deals with issues related to the "unauthorized" use of others' code and features. These issues can only be resolved through proper legalization by the original authors themselves.

We also considered the idea of packaging it as a patch, but we haven't received any decisive responses or seen any corresponding actions in this direction. That said, we are actively communicating with the original authors to push forward with further compliance measures.

At the moment, this remains an area with significant room for improvement and requires more in-depth discussion. We appreciate your input and will continue to explore ways to address these challenges.
